services:
  db_dev:
    image: postgres
    ports:
      - "${LC_DEV_PORT}:5432"
    volumes:
      - db_dev_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${LC_POSTGRES_PASSWORD}
      POSTGRES_USER: ${LC_POSTGRES_USER}
      POSTGRES_DB: ${LC_DEV_DB}
  db_test:
    image: postgres
    ports:
      - "${LC_TEST_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${LC_POSTGRES_PASSWORD}
      POSTGRES_USER: ${LC_POSTGRES_USER}
      POSTGRES_DB: ${LC_TEST_DB}
volumes:
  db_dev_data:

      